language: java
cache:
  timeout: 1000
  directories:
  - $HOME/.m2
jdk:
- openjdk8
- openjdk11
os:
  - linux
env:
 - TEST_CASE="RepositoryApplication"
 - TEST_CASE="RestApplication"
before_install:
    - git clone https://github.com/jeddict/netbeans-modeler.git ~/builds/netbeans-modeler
    - pushd ~/builds/netbeans-modeler
    - mvn clean install -q
    - popd

    - git clone https://github.com/jeddict/jeddict.git ~/builds/jeddict
    - pushd ~/builds/jeddict
    - mvn clean install -DskipTests -q
    - popd
    
script:
    - mvn test -B -Dtestcase=${TEST_CASE}
