version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/jakarta-ee/src/main/resources/io/github/jeddict/template/repository/pom"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"

  - package_manager: "java:maven"
    directory: "/rest/src/main/java/io/github/jeddict/template/logger/pom"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"

  - package_manager: "java:maven"
    directory: "/rest/src/main/java/io/github/jeddict/template/rest/pom"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/common/arquillian"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/micro"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"  
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/micro/arquillian"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"  
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/micro/docker"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"  
 
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/persistence/provider/hibernate"
    update_schedule: "weekly"
    default_labels:
      - "dependencies" 

  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/server/arquillian"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"  
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/server/docker/arquillian"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"  
      
  - package_manager: "java:maven"
    directory: "runtime/src/main/resources/io/github/jeddict/runtime/template/payara/server/no_docker/arquillian"
    update_schedule: "weekly"
    default_labels:
      - "dependencies" 

      